base:
  project: banknote-project
  random_state: 42
  target_col: class

data_source:
  s3_source: data_given\bank.csv

load_data:
  raw_dataset_csv: data\raw\bank.csv

split_data:
  train_path: data\processed\train_bank.csv
  test_path: data\processed\test_bank.csv
  test_size: 0.2

estimators:
  SVM:
    C: 1.0

model_dir: saved_models

reports:
  params: report\params.json
  scores: report\scores.json